ALTER TABLE movies ADD COLUMN id_new SERIAL PRIMARY KEY; -- CREATE NEW ID
UPDATE movies SET id_new = id; -- SWITCH VALUE id TO id_new
ALTER TABLE movies DROP COLUMN id; -- DROP OLD ID
ALTER TABLE movies RENAME COLUMN id_new TO id; -- RENAME NEW ID